# Generated by Django 3.0.8 on 2020-08-08 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bidPrice',
        ),
        migrations.AddField(
            model_name='bid',
            name='bidObject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.Listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='bidValue',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.Listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='basePrice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('vehicle', 'Vehicle'), ('fashion', 'Fashion'), ('other', 'Other')], default='Other', max_length=11),
        ),
        migrations.AddField(
            model_name='listing',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
