# Generated by Django 3.0.8 on 2020-08-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200808_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('other', ''), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('vehicle', 'Vehicle'), ('fashion', 'Fashion')], max_length=11),
        ),
    ]
